### ISSUE TITLE
When you say "WIP" what does that mean?

### ISSUE THREAD

**Issue by CrashyBang** [lukeed/pwa#74]
Would it be possible to get some clarification on the "WIP" status?

Is this stable enough to use in a pet project? Business project? etc...

I am really keen on trying to use this for a Svelte project as a hobby so I don't mind debugging issues and giving back to the project just wanted to get some insight as to where it stands from your perspective?

Would potentially be good to highlight what this means in the README to?

**Comment by lukeed** [comment]
Hey, 

WIP is pretty literal here. There are things in progress, which is to say I don't consider this finalized and/or feature complete yet.

It's not 1.0, which means that things _could_ change - but so far it's been stable. In pre-1.0, minors are treated as possible breakings but we've not had any yet aside from Node 6 to Node 8 minimum.

I, along with my previous company and past/current clients, have been using this to power a multitude of production apps. It's certainly prod-ready because PWA is just a thin layer over webpack.

**Comment by CrashyBang** [comment]
Perfect :) I look forward to digging in!
